version: "3.7"

services:

  chat_db:
    container_name: chat_db
    image: "postgres:13-alpine"
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_DB=my_postgres_db  # Переменная окружения для создания базы данных
      - POSTGRES_PASSWORD=postgres_password
      - POSTGRES_USER=postgres_user
      - LANG=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - LC_MESSAGES=en_US.UTF-8
    networks:
      my_api_network:
    ports:
      - "5433:5432"

networks:
  my_api_network:
    driver: bridge